CREATE TYPE ImageListType AS TABLE OF BLOB;

ALTER TABLE MOVIES 
ADD  
Images ImageListType
nested table Images store as ImagesTable;

CREATE OR REPLACE VIEW VIDEO_RENT.MOVIES_VIEW 
AS
SELECT ID, TITLE, DESCRIPTION, PHOTO, IMAGES, LANGUAGE, RELEASE_DATE, RUN_TIME 
FROM VIDEO_RENT.MOVIES 
WHERE deleted_by IS NULL;