DROP TABLE MOVIES CASCADE CONSTRAINTS;

CREATE TABLE MOVIES(
    Id NUMBER GENERATED ALWAYS as IDENTITY(START with 1 INCREMENT by 1) PRIMARY KEY,
    Title VARCHAR2(100),
    Description VARCHAR2(100),
    Photo BLOB,
    Release_date DATE,
    Run_time INTERVAL DAY TO SECOND,
    Language REFERENCES LANGUAGES (Id)
);

DROP TABLE LANGUAGES CASCADE CONSTRAINTS;

CREATE TABLE LANGUAGES(
    Id NUMBER GENERATED ALWAYS as IDENTITY(START with 1 INCREMENT by 1) PRIMARY KEY,
    Name VARCHAR2(100)
);

DROP TABLE GANRES CASCADE CONSTRAINTS;

CREATE TABLE GANRES(
    Id NUMBER GENERATED ALWAYS as IDENTITY(START with 1 INCREMENT by 1) PRIMARY KEY,
    Name VARCHAR2(100)
);

DROP TABLE MOVIES_GANRES CASCADE CONSTRAINTS;

CREATE TABLE MOVIES_GANRES(
    Movie_id NUMBER REFERENCES MOVIES (Id),
    Ganre_id NUMBER REFERENCES GANRES (Id)
);

DROP TABLE MOVIES_STATISTICS CASCADE CONSTRAINTS;

CREATE TABLE MOVIES_STATISTICS(
    Movie_id NUMBER REFERENCES MOVIES (Id) PRIMARY KEY,
    Views_count NUMBER
);
