CREATE OR REPLACE VIEW VIDEO_RENT.TOP_10_MOVIES_VIEW 
AS
SELECT ID, TITLE, PHOTO, s.VIEWS_COUNT
FROM VIDEO_RENT.MOVIES_VIEW m
LEFT JOIN VIDEO_RENT.movies_statistics s ON m.id = s.movie_id
ORDER BY s.views_count DESC nulls last
FETCH FIRST 10 ROWS ONLY;